/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BikeService } from "../bike.service";
import { BikeCreateInput } from "./BikeCreateInput";
import { Bike } from "./Bike";
import { BikeFindManyArgs } from "./BikeFindManyArgs";
import { BikeWhereUniqueInput } from "./BikeWhereUniqueInput";
import { BikeUpdateInput } from "./BikeUpdateInput";
import { TripFindManyArgs } from "../../trip/base/TripFindManyArgs";
import { Trip } from "../../trip/base/Trip";
import { TripWhereUniqueInput } from "../../trip/base/TripWhereUniqueInput";

export class BikeControllerBase {
  constructor(protected readonly service: BikeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Bike })
  async createBike(@common.Body() data: BikeCreateInput): Promise<Bike> {
    return await this.service.createBike({
      data: data,
      select: {
        brand: true,
        createdAt: true,
        id: true,
        model: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Bike] })
  @ApiNestedQuery(BikeFindManyArgs)
  async bikes(@common.Req() request: Request): Promise<Bike[]> {
    const args = plainToClass(BikeFindManyArgs, request.query);
    return this.service.bikes({
      ...args,
      select: {
        brand: true,
        createdAt: true,
        id: true,
        model: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Bike })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async bike(
    @common.Param() params: BikeWhereUniqueInput
  ): Promise<Bike | null> {
    const result = await this.service.bike({
      where: params,
      select: {
        brand: true,
        createdAt: true,
        id: true,
        model: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Bike })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBike(
    @common.Param() params: BikeWhereUniqueInput,
    @common.Body() data: BikeUpdateInput
  ): Promise<Bike | null> {
    try {
      return await this.service.updateBike({
        where: params,
        data: data,
        select: {
          brand: true,
          createdAt: true,
          id: true,
          model: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Bike })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBike(
    @common.Param() params: BikeWhereUniqueInput
  ): Promise<Bike | null> {
    try {
      return await this.service.deleteBike({
        where: params,
        select: {
          brand: true,
          createdAt: true,
          id: true,
          model: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/trips")
  @ApiNestedQuery(TripFindManyArgs)
  async findTrips(
    @common.Req() request: Request,
    @common.Param() params: BikeWhereUniqueInput
  ): Promise<Trip[]> {
    const query = plainToClass(TripFindManyArgs, request.query);
    const results = await this.service.findTrips(params.id, {
      ...query,
      select: {
        bike: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endDate: true,
        id: true,

        pack: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trips")
  async connectTrips(
    @common.Param() params: BikeWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        connect: body,
      },
    };
    await this.service.updateBike({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trips")
  async updateTrips(
    @common.Param() params: BikeWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        set: body,
      },
    };
    await this.service.updateBike({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trips")
  async disconnectTrips(
    @common.Param() params: BikeWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        disconnect: body,
      },
    };
    await this.service.updateBike({
      where: params,
      data,
      select: { id: true },
    });
  }
}
