/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PackService } from "../pack.service";
import { PackCreateInput } from "./PackCreateInput";
import { Pack } from "./Pack";
import { PackFindManyArgs } from "./PackFindManyArgs";
import { PackWhereUniqueInput } from "./PackWhereUniqueInput";
import { PackUpdateInput } from "./PackUpdateInput";
import { TripFindManyArgs } from "../../trip/base/TripFindManyArgs";
import { Trip } from "../../trip/base/Trip";
import { TripWhereUniqueInput } from "../../trip/base/TripWhereUniqueInput";

export class PackControllerBase {
  constructor(protected readonly service: PackService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pack })
  async createPack(@common.Body() data: PackCreateInput): Promise<Pack> {
    return await this.service.createPack({
      data: data,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        waterproof: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Pack] })
  @ApiNestedQuery(PackFindManyArgs)
  async packs(@common.Req() request: Request): Promise<Pack[]> {
    const args = plainToClass(PackFindManyArgs, request.query);
    return this.service.packs({
      ...args,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        waterproof: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pack })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async pack(
    @common.Param() params: PackWhereUniqueInput
  ): Promise<Pack | null> {
    const result = await this.service.pack({
      where: params,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        waterproof: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pack })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePack(
    @common.Param() params: PackWhereUniqueInput,
    @common.Body() data: PackUpdateInput
  ): Promise<Pack | null> {
    try {
      return await this.service.updatePack({
        where: params,
        data: data,
        select: {
          capacity: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
          waterproof: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pack })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePack(
    @common.Param() params: PackWhereUniqueInput
  ): Promise<Pack | null> {
    try {
      return await this.service.deletePack({
        where: params,
        select: {
          capacity: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
          waterproof: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/trips")
  @ApiNestedQuery(TripFindManyArgs)
  async findTrips(
    @common.Req() request: Request,
    @common.Param() params: PackWhereUniqueInput
  ): Promise<Trip[]> {
    const query = plainToClass(TripFindManyArgs, request.query);
    const results = await this.service.findTrips(params.id, {
      ...query,
      select: {
        bike: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endDate: true,
        id: true,

        pack: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trips")
  async connectTrips(
    @common.Param() params: PackWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        connect: body,
      },
    };
    await this.service.updatePack({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trips")
  async updateTrips(
    @common.Param() params: PackWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        set: body,
      },
    };
    await this.service.updatePack({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trips")
  async disconnectTrips(
    @common.Param() params: PackWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        disconnect: body,
      },
    };
    await this.service.updatePack({
      where: params,
      data,
      select: { id: true },
    });
  }
}
